### ISSUE TITLE
Installing 3rd party programs outside of module: LinuxBrew

### ISSUE THREAD

**Issue by jsta** [lxwrght/HPCC-template#1]
My biggest pain-point with the MSU system is that I cannot install 3rd party programs from standard repositories (e.g. cannot `apt-get install` programs).  I was pointed to LinuxBrew but I had no success there either; At least not without a lot of effort. Do you have any experience with this?

**Comment by jsta** [comment]
I would discount the HPCC entirely in favor of [Cyverse](http://www.cyverse.org/) (where I can `apt-get` all I want) if it weren't for the strict storage and runtime limitations.

**Comment by lxwrght** [comment]
Per our discussion earlier, I looked around the HPCC User Manual and I couldn't find any documentation on how to request the purchase of additional software by iCER (which I was surprised about). But no, fortunately they have the programs I need (R & JAGS) and do not have any experience with accessing 3rd party programs. Thanks for the question!

**Comment by jsta** [comment]
For posterity, I will say that I am not looking for iCER to purchase software. Rather, I am looking to install free software using the Linux equivalent of an app-store.

**Comment by lxwrght** [comment]
I see. I still don't see why iCER would be unwilling to acquire a free software program (for example, they have R). But yes, I do see it's frustrating that you are unable to access a software program that you can normally use on your own machine.
